version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
  - package-ecosystem: "docker"
    directories:
      - "docker/backup-uploader"
      - "docker/kubectl-bats"
      - "docker/debian-s6-java25"
      - "docker/ubi8-s6-java21"
      - "docker/ubi8-s6-java25"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
